/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class MapAsyncServer {
  constructor(mapFn: ((arg: Datum) => Promise<Array<Message>>), sockFile?: string | undefined | null, infoFile?: string | undefined | null)
  start(): Promise<void>
  stop(): void
}

export interface Datum {
  /** Set of keys in the (key, value) terminology of map/reduce paradigm. */
  keys: Array<string>
  /** The value in the (key, value) terminology of map/reduce paradigm. */
  value: Buffer
  /**
   * [watermark](https://numaflow.numaproj.io/core-concepts/watermarks/) represented by time is a
   * guarantee that we will not see an element older than this time.
   */
  watermark: Date
  /** Time of the element as seen at source or aligned after a reduce operation. */
  eventtime: Date
  /** Headers for the message. */
  headers: Record<string, string>
}

export interface Message {
  /**
   * Keys are a collection of strings which will be passed on to the next vertex as is. It can
   * be an empty collection.
   */
  keys?: Array<string>
  /** Value is the value passed to the next vertex. */
  value: Buffer
  /** Tags are used for [conditional forwarding](https://numaflow.numaproj.io/user-guide/reference/conditional-forwarding/). */
  tags?: Array<string>
}

export declare function messageToDrop(): Message
